version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "pr:workflows"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    labels:
      - "pr:gradle-plugins"
