name: 'Setup Java and Gradle'
description: 'Sets up JDK 17 and Gradle with caching for faster builds'

inputs:
  cache-read-only:
    description: 'Whether Gradle cache is read-only'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
